= Financial Status API Guide
include::common/config.adoc[]

(uk.gov.digital.ho.proving.financialstatus)

= API Overview

== Introduction
This document describes the Financial Status API, a REST service that exchanges JSON over HTTP and exposes information
relating to an individual's financial status and income. This guide has three main sections:

 . <<API Overview>> - Information, guidance, and conventions that apply across this API, such as access control or the use of HTTP verbs.
 . <<Resources>> - Details of the resources exposed through this API and the operations available against those resources.
 . <<Supplementary>> - Supporting information such as contact details and key terms.

For further assistance see the <<Contact>> section.

== Versioning
This is version 1 of the income proving API. In this version all resource URIs are prefixed with:

`/pttg/financialstatusservice/v1/`

== Schema
include::common/schema.adoc[]

== HTTP Conventions
include::common/http-conventions.adoc[]

== Headers
include::common/headers.adoc[]

== Errors
include::common/errors.adoc[]

== Hypermedia
include::common/hypermedia.adoc[]

== Authentication and Authorization
include::common/auth.adoc[]

'''
<<<

= Resources

[.lead]
This API exposes financial status information relating to an individual. The central resource is the
`Individual`, which represents a person and is typically identified by National Insurance Number. For a given
`Individual`, this API provides access to a child resource describing details of the individual's financial status, the
`Financial Status` resource. The API also provides access to the individuals `Bank Account` details.


== Account

The Account resource represents a bank account, typically identified by it's sort code and account number.

There are currently no operations for directly accessing the `Account`.

== Financial Status

`Financial Status` is a child of the `Account` resource. All operations regarding Financial Status are descendants
of an account.


==== Example request

include::{snippets}/financial-status/http-request.adoc[]

include::{snippets}/financial-status/curl-request.adoc[]


==== Request Parameters

include::{snippets}/financial-status/path-parameters.adoc[]

include::{snippets}/financial-status/request-parameters.adoc[]


==== Example of a successful response

include::{snippets}/financial-status/http-response.adoc[]


==== Financial Status response content

include::{snippets}/financial-status/response-fields.adoc[]


<<<
= Supplementary

== Support
include::common/contact.adoc[]

include::common/licence.adoc[]

== Glossary
include::common/glossary.adoc[]
